// Parsed from Frontier Airlines route list
// This module exports airport codes, names, and valid routes

// Map of airport codes to full names
const AIRPORTS = {
  'BQN': 'Aguadilla, PR',
  'ATL': 'Atlanta, GA',
  'AUS': 'Austin, TX',
  'BWI': 'Baltimore, MD',
  'XNA': 'Bentonville/Fayetteville, AR',
  'BOI': 'Boise, ID',
  'BOS': 'Boston, MA',
  'BGI': 'Bridgetown, Barbados',
  'BUF': 'Buffalo, NY',
  'BUR': 'Burbank, CA',
  'BTV': 'Burlington, VT',
  'SJD': 'Cabo San Lucas, MX',
  'CUN': 'Cancun, MX',
  'CID': 'Cedar Rapids, IA',
  'CHS': 'Charleston, SC',
  'CLT': 'Charlotte, NC',
  'ORD': 'Chicago, IL',
  'CVG': 'Cincinnati, OH',
  'CLE': 'Cleveland, OH',
  'CMH': 'Columbus, OH',
  'CRP': 'Corpus Christi, TX',
  'DFW': 'Dallas, TX',
  'DEN': 'Denver, CO',
  'DSM': 'Des Moines, IA',
  'DTW': 'Detroit, MI',
  'ELP': 'El Paso, TX',
  'FAR': 'Fargo, ND',
  'FLL': 'Fort Lauderdale, FL',
  'RSW': 'Fort Myers, FL',
  'GRR': 'Grand Rapids, MI',
  'GRB': 'Green Bay, WI',
  'GUA': 'Guatemala City, Guatemala',
  'MDT': 'Harrisburg, PA',
  'BDL': 'Hartford, CT',
  'IAH': 'Houston, TX',
  'IND': 'Indianapolis, IN',
  'ISP': 'Islip, NY',
  'JAX': 'Jacksonville, FL',
  'MCI': 'Kansas City, MO',
  'TYS': 'Knoxville, TN',
  'LAS': 'Las Vegas, NV',
  'LIT': 'Little Rock, AR',
  'LAX': 'Los Angeles, CA',
  'MSN': 'Madison, WI',
  'MEM': 'Memphis, TN',
  'MIA': 'Miami, FL',
  'MKE': 'Milwaukee, WI',
  'MSP': 'Minneapolis/St. Paul, MN',
  'MSO': 'Missoula, MT',
  'MBJ': 'Montego Bay, Jamaica',
  'MYR': 'Myrtle Beach, SC',
  'BNA': 'Nashville, TN',
  'NAS': 'Nassau, Bahamas',
  'MSY': 'New Orleans, LA',
  'LGA': 'New York City, NY',
  'EWR': 'Newark, NJ',
  'ORF': 'Norfolk, VA',
  'OKC': 'Oklahoma City, OK',
  'OMA': 'Omaha, NE',
  'ONT': 'Ontario/LA, CA',
  'AUA': 'Oranjestad, Aruba',
  'MCO': 'Orlando, FL',
  'PSP': 'Palm Springs, CA',
  'PNS': 'Pensacola, FL',
  'PHL': 'Philadelphia, PA',
  'PHX': 'Phoenix, AZ',
  'PIT': 'Pittsburgh, PA',
  'PSE': 'Ponce, PR',
  'POS': 'Port-of-Spain, Trinidad',
  'PWM': 'Portland, ME',
  'PDX': 'Portland, OR',
  'PLS': 'Providenciales, Turks and Caicos',
  'POP': 'Puerto Plata, Dominican Republic',
  'PVR': 'Puerto Vallarta, Mexico',
  'PUJ': 'Punta Cana, Dominican Republic',
  'RDU': 'Raleigh, NC',
  'RNO': 'Reno, NV',
  'RIC': 'Richmond, VA',
  'SMF': 'Sacramento, CA',
  'STX': 'Saint Croix, USVI',
  'SLC': 'Salt Lake City, UT',
  'SAT': 'San Antonio, TX',
  'SAN': 'San Diego, CA',
  'SFO': 'San Francisco, CA',
  'SJC': 'San Jose, CA',
  'SJO': 'San Jose, Costa Rica',
  'SJU': 'San Juan, PR',
  'SAP': 'San Pedro Sula, Honduras',
  'SAL': 'San Salvador, El Salvador',
  'SNA': 'Santa Ana, CA',
  'STI': 'Santiago de los Caballeros, Dominican Republic',
  'SDQ': 'Santo Domingo, Dominican Republic',
  'SRQ': 'Sarasota, FL',
  'SAV': 'Savannah, GA',
  'SEA': 'Seattle, WA',
  'FSD': 'Sioux Falls, SD',
  'GEG': 'Spokane, WA',
  'STL': 'St. Louis, MO',
  'SXM': 'St. Maarten',
  'ANU': 'St. John\'s, Antigua',
  'STT': 'St. Thomas, USVI',
  'SYR': 'Syracuse, NY',
  'TPA': 'Tampa, FL',
  'TTN': 'Trenton, NJ',
  'TUS': 'Tucson, AZ',
  'TUL': 'Tulsa, OK',
  'EGE': 'Vail, CO',
  'DCA': 'Washington, D.C.',
  'PBI': 'West Palm Beach, FL'
};

// Map of origin airports to valid destination airports
const ROUTES = {
  'BQN': ['MIA', 'MCO'],
  'ATL': ['AUS', 'BWI', 'BOS', 'BUF', 'SJD', 'CUN', 'ORD', 'CVG', 'CLE', 'CMH', 'DFW', 'DEN', 'DTW', 'FLL', 'RSW', 'GUA', 'BDL', 'IAH', 'IND', 'ISP', 'JAX', 'MCI', 'LAS', 'LAX', 'MEM', 'MIA', 'MKE', 'MSP', 'MBJ', 'NAS', 'MSY', 'LGA', 'EWR', 'ORF', 'OKC', 'OMA', 'AUA', 'MCO', 'PHL', 'PHX', 'PIT', 'PLS', 'PVR', 'PUJ', 'RDU', 'RIC', 'SAT', 'SFO', 'SJO', 'SJU', 'SAP', 'SAL', 'STL', 'SXM', 'SYR', 'TPA', 'TTN', 'DCA', 'PBI'],
  'AUS': ['ATL', 'ORD', 'CVG', 'CLE', 'DEN', 'LAS', 'MIA', 'MCO', 'PHL', 'PHX'],
  'BWI': ['ATL', 'CLT', 'ORD', 'DFW', 'DEN', 'DTW', 'MIA', 'MCO', 'SJU', 'TPA'],
  'XNA': ['DEN'],
  'BOI': ['DEN'],
  'BOS': ['ATL', 'CLT', 'CVG', 'CLE', 'DFW', 'MIA', 'MCO', 'PHL', 'RDU', 'SJU', 'TPA'],
  'BGI': ['SJU'],
  'BUF': ['ATL', 'CLT', 'DEN', 'RSW', 'MCO', 'RDU', 'TPA'],
  'BUR': ['DEN', 'PHX', 'SFO'],
  'BTV': ['MCO', 'TPA'],
  'SJD': ['ATL', 'DEN', 'LAS'],
  'CUN': ['ATL', 'ORD', 'CVG', 'CLE', 'DFW', 'DEN', 'IAH', 'MIA', 'MCO', 'PHL', 'STL'],
  'CID': ['DEN'],
  'CHS': ['DFW', 'PHL'],
  'CLT': ['BWI', 'BOS', 'BUF', 'ORD', 'CLE', 'DFW', 'DEN', 'IAH', 'MIA', 'LGA', 'MCO', 'PHL', 'SJU'],
  'ORD': ['ATL', 'AUS', 'BWI', 'CUN', 'CLT', 'DFW', 'DEN', 'RSW', 'IAH', 'LAS', 'LAX', 'MIA', 'MSP', 'BNA', 'LGA', 'EWR', 'MCO', 'PHL', 'PHX', 'PUJ', 'RDU', 'SLC', 'SRQ', 'TPA', 'PBI'],
  'CVG': ['ATL', 'AUS', 'BOS', 'CUN', 'DFW', 'DEN', 'FLL', 'RSW', 'IAH', 'LAS', 'MIA', 'LGA', 'MCO', 'PHX', 'SRQ', 'TPA', 'PBI'],
  'CLE': ['ATL', 'AUS', 'BOS', 'CUN', 'CLT', 'DFW', 'DEN', 'FLL', 'RSW', 'LAS', 'MIA', 'MYR', 'BNA', 'LGA', 'MCO', 'PHX', 'PUJ', 'RDU', 'SJU', 'SRQ', 'TPA', 'PBI'],
  'CMH': ['ATL', 'DEN', 'MCO'],
  'CRP': ['DEN'],
  'DFW': ['ATL', 'BWI', 'BOS', 'CUN', 'CHS', 'CLT', 'ORD', 'CVG', 'CLE', 'DEN', 'DTW', 'ELP', 'GUA', 'IAH', 'IND', 'JAX', 'LAS', 'LAX', 'MIA', 'MSP', 'LGA', 'ORF', 'ONT', 'MCO', 'PHL', 'PHX', 'PDX', 'PVR', 'RDU', 'SLC', 'SAN', 'SFO', 'SJU', 'SAL', 'SEA', 'STL', 'TPA', 'TUS', 'EGE', 'DCA'],
  'DEN': ['ATL', 'AUS', 'BWI', 'XNA', 'BOI', 'BUF', 'BUR', 'SJD', 'CUN', 'CID', 'CLT', 'ORD', 'CVG', 'CLE', 'CMH', 'CRP', 'DFW', 'DSM', 'DTW', 'ELP', 'FAR', 'RSW', 'GRR', 'GRB', 'IAH', 'IND', 'MCI', 'TYS', 'LAS', 'LIT', 'LAX', 'MSN', 'MEM', 'MIA', 'MKE', 'MSP', 'MSO', 'BNA', 'MSY', 'LGA', 'OKC', 'OMA', 'ONT', 'MCO', 'PSP', 'PNS', 'PHL', 'PHX', 'PIT', 'PDX', 'PVR', 'RDU', 'RNO', 'RIC', 'SMF', 'SLC', 'SAT', 'SAN', 'SFO', 'SJC', 'SNA', 'SEA', 'FSD', 'GEG', 'STL', 'TPA', 'TUS', 'TUL', 'EGE', 'DCA'],
  'DSM': ['DEN', 'MCO'],
  'DTW': ['ATL', 'BWI', 'DFW', 'DEN', 'RSW', 'LAS', 'MCO', 'PHX', 'RDU', 'TPA'],
  'ELP': ['DFW', 'DEN', 'LAS'],
  'FAR': ['DEN', 'MCO'],
  'FLL': ['ATL', 'CVG', 'CLE', 'ISP', 'PHL', 'SJU'],
  'RSW': ['ATL', 'BUF', 'ORD', 'CVG', 'CLE', 'DEN', 'DTW', 'GRR', 'ISP', 'PHL', 'TTN'],
  'GRR': ['DEN', 'RSW', 'MCO', 'TPA'],
  'GRB': ['DEN'],
  'GUA': ['ATL', 'DFW', 'MIA', 'MCO'],
  'MDT': ['MCO'],
  'BDL': ['ATL', 'MIA', 'MCO', 'SJU', 'TPA'],
  'IAH': ['ATL', 'CUN', 'CLT', 'ORD', 'CVG', 'DFW', 'DEN', 'LAS', 'LAX', 'MIA', 'ONT', 'MCO', 'PHX', 'RDU', 'TPA'],
  'IND': ['ATL', 'DFW', 'DEN', 'MCO', 'RDU', 'TPA'],
  'ISP': ['ATL', 'FLL', 'RSW', 'MYR', 'MCO', 'RDU', 'TPA', 'PBI'],
  'JAX': ['ATL', 'DFW', 'PHL', 'SJU'],
  'MCI': ['ATL', 'DEN', 'TPA'],
  'TYS': ['DEN'],
  'LAS': ['ATL', 'AUS', 'SJD', 'ORD', 'CVG', 'CLE', 'DFW', 'DEN', 'DTW', 'ELP', 'IAH', 'LAX', 'MIA', 'LGA', 'OKC', 'ONT', 'MCO', 'PHL', 'PHX', 'PDX', 'RDU', 'RNO', 'SMF', 'SLC', 'SAT', 'SAN', 'SFO', 'SJC', 'SNA', 'SEA', 'STL', 'TPA', 'TUS'],
  'LIT': ['DEN'],
  'LAX': ['ATL', 'ORD', 'DFW', 'DEN', 'IAH', 'LAS', 'LGA', 'MCO', 'PHL', 'PHX', 'PDX', 'SMF', 'SLC', 'SFO', 'SJC', 'SEA'],
  'MSN': ['DEN', 'MCO'],
  'MEM': ['ATL', 'DEN'],
  'MIA': ['BQN', 'ATL', 'AUS', 'BWI', 'BOS', 'CUN', 'CLT', 'ORD', 'CVG', 'CLE', 'DFW', 'DEN', 'GUA', 'BDL', 'IAH', 'LAS', 'LGA', 'PHL', 'PUJ', 'RDU', 'SJU', 'SAP', 'SAL', 'SDQ', 'DCA'],
  'MKE': ['ATL', 'DEN', 'MCO', 'TPA'],
  'MSP': ['ATL', 'ORD', 'DFW', 'DEN', 'MCO', 'PHX'],
  'MSO': ['DEN'],
  'MBJ': ['ATL', 'PHL'],
  'MYR': ['CLE', 'ISP', 'PHL'],
  'BNA': ['ORD', 'CLE', 'DEN', 'MCO', 'PHL'],
  'NAS': ['ATL'],
  'MSY': ['ATL', 'DEN', 'MCO', 'PHL'],
  'LGA': ['ATL', 'CLT', 'ORD', 'CVG', 'CLE', 'DFW', 'DEN', 'LAS', 'LAX', 'MIA', 'MCO', 'RDU', 'SJU', 'TPA'],
  'EWR': ['ATL', 'ORD', 'SJU'],
  'ORF': ['ATL', 'DFW', 'MCO'],
  'OKC': ['ATL', 'DEN', 'LAS', 'MCO'],
  'OMA': ['ATL', 'DEN', 'MCO'],
  'ONT': ['DFW', 'DEN', 'IAH', 'LAS', 'PDX', 'SMF', 'SLC', 'SFO', 'SEA'],
  'AUA': ['ATL'],
  'MCO': ['BQN', 'ATL', 'AUS', 'BWI', 'BOS', 'BUF', 'BTV', 'CUN', 'CLT', 'ORD', 'CVG', 'CLE', 'CMH', 'DFW', 'DEN', 'DSM', 'DTW', 'FAR', 'GRR', 'GUA', 'MDT', 'BDL', 'IAH', 'IND', 'ISP', 'LAS', 'LAX', 'MSN', 'MKE', 'MSP', 'BNA', 'MSY', 'LGA', 'ORF', 'OKC', 'OMA', 'PHL', 'PHX', 'PIT', 'PSE', 'PWM', 'PUJ', 'RDU', 'SAT', 'SFO', 'SJU', 'SAL', 'SDQ', 'STL', 'SXM', 'SYR', 'TTN', 'DCA'],
  'PSP': ['DEN', 'SFO'],
  'PNS': ['DEN'],
  'PHL': ['ATL', 'AUS', 'BOS', 'CUN', 'CHS', 'CLT', 'ORD', 'DFW', 'DEN', 'FLL', 'RSW', 'JAX', 'LAS', 'LAX', 'MIA', 'MBJ', 'MYR', 'BNA', 'MSY', 'MCO', 'PIT', 'PUJ', 'RDU', 'SJU', 'SDQ', 'SRQ', 'SAV', 'TPA', 'PBI'],
  'PHX': ['ATL', 'AUS', 'BUR', 'ORD', 'CVG', 'CLE', 'DFW', 'DEN', 'DTW', 'IAH', 'LAS', 'LAX', 'MSP', 'MCO', 'PDX', 'RNO', 'SLC', 'SAT', 'SAN', 'SFO', 'SJC', 'SNA', 'SEA', 'GEG'],
  'PIT': ['ATL', 'DEN', 'MCO', 'PHL'],
  'PSE': ['MCO'],
  'POS': ['SJU'],
  'PWM': ['MCO', 'TPA'],
  'PDX': ['DFW', 'DEN', 'LAS', 'LAX', 'ONT', 'PHX', 'SLC', 'SFO'],
  'PLS': ['ATL'],
  'POP': ['SJU'],
  'PVR': ['ATL', 'DFW', 'DEN'],
  'PUJ': ['ATL', 'ORD', 'CLE', 'MIA', 'MCO', 'PHL', 'SJU', 'STL', 'TPA'],
  'RDU': ['ATL', 'BOS', 'BUF', 'ORD', 'CLE', 'DFW', 'DEN', 'DTW', 'IAH', 'IND', 'ISP', 'LAS', 'MIA', 'LGA', 'MCO', 'PHL', 'SJU', 'SYR', 'TPA'],
  'RNO': ['DEN', 'LAS', 'PHX'],
  'RIC': ['ATL', 'DEN'],
  'SMF': ['DEN', 'LAS', 'LAX', 'ONT', 'SAN'],
  'STX': ['SJU'],
  'SLC': ['ORD', 'DFW', 'DEN', 'LAS', 'LAX', 'ONT', 'PHX', 'PDX', 'SFO', 'SNA', 'SEA'],
  'SAT': ['ATL', 'DEN', 'LAS', 'MCO', 'PHX'],
  'SAN': ['DFW', 'DEN', 'LAS', 'PHX', 'SMF', 'SFO'],
  'SFO': ['ATL', 'BUR', 'DFW', 'DEN', 'LAS', 'LAX', 'ONT', 'MCO', 'PSP', 'PHX', 'PDX', 'SLC', 'SAN', 'SNA', 'EGE'],
  'SJC': ['DEN', 'LAS', 'LAX', 'PHX'],
  'SJO': ['ATL'],
  'SJU': ['ATL', 'BWI', 'BOS', 'BGI', 'CLT', 'CLE', 'DFW', 'FLL', 'BDL', 'JAX', 'MIA', 'LGA', 'EWR', 'MCO', 'PHL', 'POS', 'POP', 'PUJ', 'RDU', 'STX', 'STI', 'SDQ', 'ANU', 'SXM', 'STT', 'TPA', 'DCA'],
  'SAP': ['ATL', 'MIA'],
  'SAL': ['ATL', 'DFW', 'MIA', 'MCO', 'DCA'],
  'SNA': ['DEN', 'LAS', 'PHX', 'SLC', 'SFO'],
  'STI': ['SJU'],
  'SDQ': ['MIA', 'MCO', 'PHL', 'SJU', 'TPA'],
  'SRQ': ['ORD', 'CVG', 'CLE', 'PHL'],
  'SAV': ['PHL'],
  'SEA': ['DFW', 'DEN', 'LAS', 'LAX', 'ONT', 'PHX', 'SLC'],
  'FSD': ['DEN'],
  'GEG': ['DEN', 'PHX'],
  'STL': ['ATL', 'CUN', 'DFW', 'DEN', 'LAS', 'MCO', 'PUJ', 'TPA'],
  'SXM': ['ATL', 'MCO', 'SJU'],
  'ANU': ['SJU'],
  'STT': ['SJU'],
  'SYR': ['ATL', 'MCO', 'RDU'],
  'TPA': ['ATL', 'BWI', 'BOS', 'BUF', 'BTV', 'ORD', 'CVG', 'CLE', 'DFW', 'DEN', 'DTW', 'GRR', 'BDL', 'IAH', 'IND', 'ISP', 'MCI', 'LAS', 'MKE', 'LGA', 'PHL', 'PWM', 'PUJ', 'RDU', 'SJU', 'SDQ', 'STL', 'TTN', 'DCA'],
  'TTN': ['ATL', 'RSW', 'MCO', 'TPA', 'PBI'],
  'TUS': ['DFW', 'DEN', 'LAS'],
  'TUL': ['DEN'],
  'EGE': ['DFW', 'DEN', 'SFO'],
  'DCA': ['ATL', 'DFW', 'DEN', 'MIA', 'MCO', 'SJU', 'SAL', 'TPA'],
  'PBI': ['ATL', 'ORD', 'CVG', 'CLE', 'ISP', 'PHL', 'TTN']
};

module.exports = {
  AIRPORTS,
  ROUTES
};
